version: "3"
   
services:
  db:
    image: postgres
    volumes:
      - /mnt/pgdata_form_data/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=form_db
      - POSTGRES_USER=form_user
      - POSTGRES_PASSWORD=Uj8g4uxE
      - TZ=America/Managua
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - local.env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

